name: Test
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: ./scripts/sudo-ci.sh
